language:
    - python

python:
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.6"

install:
    - pip install -r requirements.txt
    - pip install pytest pycodestyle

script:
    - pycodestyle . --max-line-length=120
    - pytest

deploy:
    provider: pypi
    user: "WingC"
    password:
      secure: "CEMkKACMjttECAkqUQEZS9Pco9SmKXtHvc9v9BHc7hhu8P9BCyJBYYMHOLxVz25yX2uu4CSmq2S9NL6HzM6g2D3z0WTiiL93+/Wd9kClzCSoGlCsRywIGNEq6aBgRhKPTEor2RIvgcgw3vI3VaOUjkq9nyiUnVGBstYM9guk+Wq5JspkqUxqYYM2zYnkom4bx68khbzoF33KzrzHXuoaaTGgz+P4RGsWHNP6nuwr6MKouxCHMtgRH8mgZ2KgNQVPPBkj52bG/SZkA+Bs1DPf9etDaHq1f/btQHRMTMyGqraXR4IVuTRNR3zh2Z2LSMhxG5wSOv3dhpd2NA2ZqFGqSLmdPnjN2nTh8jIYeOguUN2MqmiUGyxxBiHqAYhcBNWr0iSQlT5yC5I7ofs2kGdKX6iMqZOUZ+U4cR6oWTv/VVZzvMMyBZd4LBIBgESo1O2mWrShvY7kvKLpifXJDc08USSEvMbk1ZSbKiceDGseI69Wkf2dIiA7EfvcBD/IUujCqjYKDyXZdalXWCKgsXDbtiYxmGWSdLRF5JMfkJub/44tWexMNHCScOdqI/4NMTNSVXXNFwvHRab8HLZOiRA/S3moSS6Wk3nDLhzJums8nmU6qjpZ+iRIIqwiccKv9vm5CsUBv9F3L9ECvhdjJBJmkxnapexZuuOI6AfAjuH2O5s="
    on:
      tags: true
      python: 3.6
